/**
 * Built-in résumé template catalog — mirrors
 * Athens/src/app/features/resumes/generator/constants/templates.ts
 * so Job Search / Agents PDF rendering can honor the same templateId.
 */

export const MONO_FONT = 'ui-monospace, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace';

export const TEMPLATES = [
  {
    id: "classic",
    name: "Classic",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "underline",
    headingAlign: "left",
    defaultHeaderAlign: "center",
    experienceLayout: "default",
    contactIcons: false,
    nameColor: "accent",
  },
  {
    id: "centered",
    name: "Centered",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "underline",
    headingAlign: "center",
    defaultHeaderAlign: "center",
    experienceLayout: "default",
    contactIcons: false,
    nameColor: "accent",
  },
  {
    id: "minimal",
    name: "Minimal",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "plain",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "default",
    contactIcons: false,
    nameColor: "accent",
  },
  {
    id: "accent-bar",
    name: "Accent Bar",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "bar",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "default",
    contactIcons: false,
    nameColor: "accent",
  },
  {
    id: "sidebar",
    name: "Two-Column",
    columns: 2,
    sidebar: ["skills", "education"],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: true,
    heading: "underline",
    headingAlign: "left",
    defaultHeaderAlign: "center",
    experienceLayout: "default",
    contactIcons: false,
    nameColor: "accent",
  },
  {
    id: "standard",
    name: "Standard",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "underline",
    headingAlign: "left",
    defaultHeaderAlign: "center",
    experienceLayout: "standard",
    contactIcons: true,
    nameColor: "accent",
    defaults: { font: "Times New Roman", accent: "#1f3a5f" },
  },
  {
    id: "compact",
    name: "Compact",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "underline",
    headingAlign: "left",
    defaultHeaderAlign: "center",
    experienceLayout: "single-line",
    contactIcons: true,
    nameColor: "accent",
    defaults: { font: "Times New Roman", accent: "#1f3a5f" },
  },
  {
    id: "modern",
    name: "Modern",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "plain",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "modern",
    contactIcons: true,
    nameColor: "accent",
    defaults: { font: "Inter", accent: "#2563eb" },
  },
  {
    id: "harvard",
    name: "Harvard",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "centered-rules",
    headingAlign: "center",
    defaultHeaderAlign: "center",
    experienceLayout: "harvard",
    contactIcons: false,
    nameColor: "text",
    defaults: { font: "Times New Roman", accent: "#1f2937" },
  },
  {
    id: "jakes",
    name: "Jake's",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "underline",
    headingAlign: "left",
    defaultHeaderAlign: "center",
    experienceLayout: "jakes",
    contactIcons: false,
    nameColor: "text",
    defaults: { font: "Georgia", accent: "#1a1a1a" },
  },
  {
    id: "bold",
    name: "Bold",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "plain",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "single-line",
    contactIcons: true,
    nameColor: "text",
    headingCase: "title",
    nameRule: true,
    topBar: true,
    headingColor: "text",
    defaults: { font: "Inter", accent: "#2f6df6" },
  },
  {
    id: "alternative",
    name: "Alternative",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "plain",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "two-col-entry",
    contactIcons: true,
    nameColor: "text",
    headingMuted: true,
    nameUppercase: true,
    cornerAccent: true,
    defaults: { font: "Inter", accent: "#2563eb" },
  },
  {
    id: "dev-compact",
    name: "Dev Compact",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "plain",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "dev",
    contactIcons: false,
    nameColor: "text",
    headingCase: "title",
    headingMuted: true,
    defaults: { font: MONO_FONT, accent: "#111827" },
  },
  {
    id: "dev",
    name: "Dev",
    columns: 1,
    sidebar: [],
    sidebarSide: "left",
    sidebarWidthPct: 34,
    sidebarTint: false,
    heading: "plain",
    headingAlign: "left",
    defaultHeaderAlign: "left",
    experienceLayout: "dev",
    contactIcons: false,
    nameColor: "text",
    headingCase: "title",
    headingMuted: true,
    labelGutter: true,
    defaults: { font: MONO_FONT, accent: "#111827" },
  },
];

/** Resolve a built-in template; uploaded DOCX ids fall back to classic. */
export function templateById(id) {
  const raw = String(id ?? "").trim();
  if (!raw || raw.startsWith("upload:")) return TEMPLATES[0];
  return TEMPLATES.find((t) => t.id === raw) ?? TEMPLATES[0];
}
