#!/usr/bin/env bash
# Apply ATHENS_API_URL into config.js (XOR+base64 encoded — no plaintext host in the zip).
# Precedence: explicit env → PUBLIC_ORIGIN → Bid-Monitor/.env → localhost default.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
CONFIG_JS="${1:-${ROOT}/config.js}"
ENCODE_PY="${ROOT}/../docker/encode-endpoint.py"

# Capture CI / pack overrides before .env can clobber them.
PRESET_API_URL="${ATHENS_API_URL:-}"
PRESET_ORIGIN="${PUBLIC_ORIGIN:-}"
PRESET_FIREBASE_KEY="${FIREBASE_WEB_API_KEY:-}"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT}/.env"
  set +a
fi

if [[ -n "${PRESET_API_URL}" ]]; then
  ATHENS_API_URL="${PRESET_API_URL}"
elif [[ -n "${PRESET_ORIGIN}" ]]; then
  ATHENS_API_URL="${PRESET_ORIGIN%/}/api"
fi

ATHENS_API_URL="${ATHENS_API_URL:-http://127.0.0.1:8979/api}"
FIREBASE_WEB_API_KEY="${PRESET_FIREBASE_KEY:-${FIREBASE_WEB_API_KEY:-}}"

if [[ ! "${ATHENS_API_URL}" =~ ^https?:// ]]; then
  echo "error: ATHENS_API_URL must be an http(s) URL, got: ${ATHENS_API_URL}" >&2
  exit 1
fi

python3 - <<PY
from pathlib import Path
import base64
import runpy

url = """${ATHENS_API_URL}""".strip().rstrip("/")
firebase_key = """${FIREBASE_WEB_API_KEY}""".strip()
if not url.endswith("/api"):
    url = url + "/api"

ns = runpy.run_path("""${ENCODE_PY}""")
token = ns["encode"](url)

text = f'''/**
 * Bid Monitor runtime config.
 * Endpoint is encoded (not plaintext). Generated by apply-env.sh / pack-extension.sh.
 */
const BidMonitorConfig = (() => {{
  const KEY = "athens-ext-cfg-v1";
  const TOKEN = {token!r};
  function decodeEndpoint(token) {{
    const raw = Uint8Array.from(atob(token), (c) => c.charCodeAt(0));
    let out = "";
    for (let i = 0; i < raw.length; i++) {{
      out += String.fromCharCode(raw[i] ^ KEY.charCodeAt(i % KEY.length));
    }}
    return out;
  }}
  return Object.freeze({{
    get ATHENS_API_URL() {{
      return decodeEndpoint(TOKEN);
    }},
    FIREBASE_WEB_API_KEY: {firebase_key!r},
  }});
}})();
'''
Path("""${CONFIG_JS}""").write_text(text)
# Confirm round-trip without printing the URL (CI logs).
decoded = ns["decode"](token)
assert decoded == url, "encode/decode mismatch"
print(f"Wrote {Path('''${CONFIG_JS}''')} (encoded endpoint, {len(token)} chars)")
PY
