#!/usr/bin/env bash
# Apply ATHENS_API_URL into config.js.
# Precedence: explicit env → PUBLIC_ORIGIN → Bid-Monitor/.env → localhost default.
# Used for local unpacked loads and by pack-extension.sh before zipping.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
CONFIG_JS="${1:-${ROOT}/config.js}"

# Capture CI / pack overrides before .env can clobber them.
PRESET_API_URL="${ATHENS_API_URL:-}"
PRESET_ORIGIN="${PUBLIC_ORIGIN:-}"

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT}/.env"
  set +a
fi

if [[ -n "${PRESET_API_URL}" ]]; then
  ATHENS_API_URL="${PRESET_API_URL}"
elif [[ -n "${PRESET_ORIGIN}" ]]; then
  ATHENS_API_URL="${PRESET_ORIGIN%/}/api"
fi

ATHENS_API_URL="${ATHENS_API_URL:-http://127.0.0.1:8979/api}"

if [[ ! "${ATHENS_API_URL}" =~ ^https?:// ]]; then
  echo "error: ATHENS_API_URL must be an http(s) URL, got: ${ATHENS_API_URL}" >&2
  exit 1
fi

python3 - <<PY
from pathlib import Path
url = """${ATHENS_API_URL}""".strip().rstrip("/")
if not url.endswith("/api"):
    url = url + "/api"
text = f'''/**
 * Bid Monitor runtime config.
 * Generated by apply-env.sh / pack-extension.sh — do not hand-edit in dist.
 */
const BidMonitorConfig = Object.freeze({{
  /** Athens-server REST API base (include /api suffix). */
  ATHENS_API_URL: {url!r},
}});
'''
Path("""${CONFIG_JS}""").write_text(text)
print(f"Wrote {Path('''${CONFIG_JS}''')} with ATHENS_API_URL={url}")
PY
