/**
 * Bid Monitor runtime config.
 * Endpoint is encoded (not plaintext). Generated by apply-env.sh / pack-extension.sh.
 */
const BidMonitorConfig = (() => {
  const KEY = "athens-ext-cfg-v1";
  const TOKEN = 'CQAcFVRcAlRKQwNTSFcDRwtZTV9cQRJdDA==';
  function decodeEndpoint(token) {
    const raw = Uint8Array.from(atob(token), (c) => c.charCodeAt(0));
    let out = "";
    for (let i = 0; i < raw.length; i++) {
      out += String.fromCharCode(raw[i] ^ KEY.charCodeAt(i % KEY.length));
    }
    return out;
  }
  return Object.freeze({
    get ATHENS_API_URL() {
      return decodeEndpoint(TOKEN);
    },
  });
})();
