export type View =
  | "dashboard"
  | "job-board"
  | "title-review"
  | "resumes"
  | "agents"
  | "mail"
  | "calendar"
  | "notion"
  | "reports"
  | "ai-usage"
  | "api-usage-monitor"
  | "firebase"
  | "bid-management"
  | "apps-plugins"
  | "changelog"
  | "settings";
