apiVersion: 1

datasources:
  - name: Athens Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Athens Google Cloud Monitoring
    uid: athens-google-cloud
    type: stackdriver
    access: proxy
    editable: false
    jsonData:
      authenticationType: jwt
      defaultProject: ${GCP_PROJECT_ID}
      clientEmail: ${GCP_MONITORING_CLIENT_EMAIL}
      tokenUri: https://oauth2.googleapis.com/token
    secureJsonData:
      privateKey: ${GCP_MONITORING_PRIVATE_KEY}
