process_names:
  - name: mongod
    comm:
      - mongod
  - name: athens
    cmdline:
      - '.*dist/main\.js.*'
  - name: prometheus
    comm:
      - prometheus
  - name: grafana
    comm:
      - grafana
      - grafana-server
  - name: cadvisor
    comm:
      - cadvisor
  - name: alertmanager
    comm:
      - alertmanager
  - name: node-exporter
    comm:
      - node_exporter
  - name: blackbox-exporter
    comm:
      - blackbox_exporter
  - name: process-exporter
    comm:
      - process-exporter
